### ISSUE TITLE
macOS: TypeError: nw_window.moveBy is not a function

### ISSUE THREAD

**Issue by m-obeid** [fifomori/chromori#4]
TypeError: nw_window.moveBy is not a function
    at Yanfly.updateResolution (<anonymous>:167:13)
    at ConfigManager.applyData (<anonymous>:693:12)
    at ConfigManager.applyData (<anonymous>:1517:34)
    at ConfigManager.applyData (<anonymous>:472:2572)
    at ConfigManager.load (rpg_managers.js:526:10)
    at Scene_Boot.create (rpg_scenes.js:351:19)
    at SceneManager.changeScene (rpg_managers.js:2009:25)
    at SceneManager.updateMain (<anonymous>:1287:9)
    at SceneManager.update (<anonymous>:1207:11)
    at TickerListener.emit (pixi.js:28596:25)
    
   Tried running the server on macOS and this happened when I tried to load the game

**Comment by cafeed28** [comment]
should be fixed in latest commit (5dadb39f9ee501d028da95130b746859cbd1ffe0)

**Comment by m-obeid** [comment]
Nope, didn't work. I tried accessing chromori running on the Mac from other devices, same error. But it works perfectly from Windows

**Comment by cafeed28** [comment]
try to run `install.sh` script again after pulling last commit

**Comment by m-obeid** [comment]
Works now interestingly enough, thanks!
